### ISSUE TITLE
version of java-model dependency

### ISSUE THREAD

**Issue by heldic** [admin-shell-io/java-serializer#1]
It'd be great if this could point to the newly released version 1.0.0 instead of 1.1.2 to avoid clashing versions when using the serializer (versions of serializer & model should/need to be in sync from now on I think): 
https://github.com/admin-shell-io/java-serializer/blob/25936a38634b3bcaeedf12251f0e41467bf2aeb9/pom.xml#L19

**Comment by alw-iwu** [comment]
${model.version} is now tied to ${revision}. Therefore, this should be fixed and can be closed by a maintainer. Was this ever a functional error or just a stylistic issue?

https://github.com/admin-shell-io/java-serializer/blob/a11b41574fcd280952803200dfbd1c91a2d7ba5d/pom.xml#L43
