### ISSUE TITLE
Values of Attribute identifierType IRI and IRDI uppercase in XML schema of specification

### ISSUE THREAD

**Issue by bs-jokri** [admin-shell-io/java-serializer#56]
Hi,

First of all, many thanks for this great library. This really helps developing for the admin shell and helps to understand the specification.

I found the following possible inconsistency:

The XML schema available here [1] defines identifier type as
```
			<simpleType>
				<restriction base="string">
					<enumeration value="Custom"/>
					<enumeration value="IRDI"/>
					<enumeration value="IRI"/>
				</restriction>
			</simpleType>
```
Whereas the XML-, JSON and AASX-Generators generate IRI and IRDI as "Iri" and "Irdi". It seems the generator lib uses another schema [2], even though both schema files seem t represent the same version of the admin shell as indicated by their namespaces ("http://www.admin-shell.io/aas/3/0").

Expected behavior: The serializer should generate AAS files according to the official schema definition to allow compatibility with other tooling (eg AASXPackageExplorer).

[1] https://github.com/admin-shell-io/aas-specs/blob/master/schemas/xml/AAS.xsd
[2] https://github.com/admin-shell-io/java-serializer/blob/main/dataformat-xml/src/main/resources/AAS.xsd

**Comment by mjacoby** [comment]
You are correct, the implementation does deviate from the specification regarding this issue. However, this is on purpose und in alignment with future/proposed changed to the specification, see the[ XML schema file on branch feature/XmlUpdate](https://github.com/admin-shell-io/aas-specs/blob/feature/XmlUpdate/schemas/xml/AAS.xsd) which says 
```
			<simpleType>
				<restriction base="string">
					<enumeration value="Custom"/>
					<enumeration value="Irdi"/>
					<enumeration value="Iri"/>
				</restriction>
			</simpleType>
```

So basically, this project is implementing a not yet officially released future version of the specification.
However, in this particular case, we could think about not enforcing/checking capitalization for enum names.

**Comment by bs-jokri** [comment]
@mjacoby thanks for pointing to the actual reason why the values are generated in this way and giving the link to the branch of the schema it refers to. By chance I have just seen that there is another branch with a [Schema version RC2 ](https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/AAS.xsd), which again seems to fall back to the all uppercase notation.

It seems the form of the identifier is still under specification. I would therefore opt for waiting until a final release of AASv3 is out and use the form, which is finally specified there. 

Are there any plans to adjust the library to the released version of AASv3, when it is available?

**Comment by mjacoby** [comment]
In general, updating the library to AAS v3.0 is planned (also it is already used by other software developed by some of the developers of this library). However, this project is currently in transition to become an Eclipse project and therefore further development will be planned and organized there.

**Comment by mjacoby** [comment]
Yes, that the one.

**Comment by sebbader** [comment]
@bs-jokri are you fine with closing the ticket here? It has been stale for a while and, as written, the new developments happen at https://github.com/eclipse-digitaltwin/aas4j.

**Comment by sebbader** [comment]
Closing as the issue has been stale for quite some time.
