### ISSUE TITLE
Deserialization of official submodel templates 

### ISSUE THREAD

**Issue by danielwilms** [admin-shell-io/java-serializer#57]
I tried the deserialisation of the released submodule templates ([example](https://github.com/admin-shell-io/submodel-templates/blob/main/published/ZVEI_Digital_Nameplate/1/0/SMT_qualified_ZVEI_Digital_Nameplate_V10.aasx) )

As the deserialisation threw an exception, I tried the validator, like:
```
 var in = new FileInputStream(_input);
 AASXValidator v = new AASXValidator(in);
 Set<String> validationResult = v.validateSchema();
 System.out.println(validationResult);
```
with `_input` as a `java.io.File`. I expected deserialisation and validation to run through, but the result was:

```
[cvc-elt.1.a: Cannot find the declaration of element 'aas:aasenv'.]
```
Any help?

**Comment by mjacoby** [comment]
I'm not the main developer of the XML de-/serializer and unfortunately do curently not have the time to investigate this in detail but I the assumption/suspicion that this may be related to a mismatch in XML namespaces, more precisely the AAS namespace which is `http://www.admin-shell.io/aas/2/0` in the provided examples but the deserializer seems to be expecting `http://www.admin-shell.io/aas/3/0` https://github.com/admin-shell-io/java-serializer/blob/4ef1837ca383bc336cee2876a6d125211d0187e1/dataformat-xml/src/main/java/io/adminshell/aas/v3/dataformat/xml/AasXmlNamespaceContext.java#L25

This probably goes deeper than just changing the version number in the namespace as it indicates that the provided examples are using AAS model v2.0 which is not supported by this library.

**Comment by sebbader-sap** [comment]
Hi @danielwilms, have you been able to solve this issue? It's been stale now for quite some time, so I will close it next week if no one comments in the meantime.

**Comment by sebbader** [comment]
Closing as the issue has been stale for quite some time.
