### ISSUE TITLE
Wrong cardinality in validator for AssetAdministrationShellEnvironment properties

### ISSUE THREAD

**Issue by mjacoby** [admin-shell-io/java-serializer#62]
**Problem**
Validator checks for the following cardinalities on properties of `AssetAdministrationShellEnvironment`

- conceptDescriptions [>=1]
- submodels [>=1]
- assetAdministrationShells[>=1]

[shapes.ttl#L315](https://github.com/admin-shell-io/java-serializer/blob/main/validator/src/main/resources/shapes.ttl#L315)

but specification does define cardinality for these properties as `[0..*]`.

Therefore, validator is not accepting some valid AASEnvironments. 

**Proposed solution**
Remove relevant SHACL shapes.

**Comment by sebbader** [comment]
I will close the issue as the new `V3.0RC02` schemas explicitly demand for `minItems=1` - different to the time when this issue has been opened. As a consequence, no further action will be applied.
@mjacoby please open the issue again at https://github.com/eclipse-digitaltwin/aas4j if you don't agree.
