### ISSUE TITLE
JsonSerializer boolean false values no output

### ISSUE THREAD

**Issue by felix-schubert** [admin-shell-io/java-serializer#65]
If submodelElementCollection attribute "ordered" or "allowDuplicates" is false, there is no output of the attribute in a json.

Example:  "allowDuplicates" = true and "ordered" = false
      "allowDuplicates" : true,
_(ordered is missing)_
Same with XmlSerializer
            <allowDuplicates>true</allowDuplicates>
            <ordered>false</ordered>

**Comment by mjacoby** [comment]
This is line with the specification (Part 1 V3.0RC01) which states that the attributes `ordered` and `allowDuplicates` are optional and by default false.

**Comment by felix-schubert** [comment]
Thank you. I see those attributes were removed in the step from Part 1 V3.0RC0**1** to Part 1 V3.0RC0**2** and I did use/read the newer specification and not the one the software complies to.
